#!/system/bin/sh

# TESTING: backup&restore
function backup_param() {
    mkdir /dev/project_wipe_backup
    cp -R /sys/devices/system/cpu/* /dev/project_wipe_backup/
}
function restore_param() {
    cp -R /dev/project_wipe_backup/* /sys/devices/system/cpu/
}

SEstatus=`getenforce`
if [ ! -f /dev/.project_wipe ] && \
    [ ! -f /dev/project_wipe_runonce ]; then
    backup_param
fi
if [ ! "restore" = "$1" ]; then
    powercfg_real $1 | tee /dev/project_wipe_state
else
    restore_param
fi
setenforce $SEstatus
